name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # build: # make sure build/ci work properly
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - run: |
  #       npm install
  #       npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        version: '1.16.2'
    - run: |
        ls -la /Library/Frameworks
        ls -la /Users/runner/hostedtoolcache
        whoami
